# Generated by Django 3.0.6 on 2020-05-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200522_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mainimage',
            field=models.ImageField(blank=True, upload_to='static/products/images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='static/products/images'),
        ),
    ]
